import type { Metadata } from 'next'
import './globals.css'
import { CSSProvider } from '@master/css.react'
import config from '../master.css'
import { ThemeProvider } from '@/contexts/theme'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning style={process.env.NODE_ENV === 'development' ? { display: 'none' } : undefined}>
            <body>
                <CSSProvider config={config}>
                    <ThemeProvider>
                        {children}
                    </ThemeProvider>
                </CSSProvider>
            </body>
        </html>
    )
}
